sudo: required
services:
  - docker

before_install:
  - docker build -t jaykishank:docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jaykishank:docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" 
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-341097230437"
  bucket_path: "Docker-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
